### ISSUE TITLE
some formula symbols might not be displayed correctly due to missing fonts symbol

### ISSUE THREAD

**Issue by tiankai** [udoyen/wps-fonts#1]

**Comment by tiankai** [comment]
1. download this repo
2. copy these font files to /usr/share/fonts/wps-office/
3. exec command "sudo chmod u+rw,g+r, o+r /usr/share/fonts/wps-office/"
4. exec command "sudo fc-cache -vfs"
**Note:**
    the folder name(**wps-office**) would be different depending on your WPS version installed on your machine.

**Comment by syedshahfaisal** [comment]
@tiankai Please Mention Repo. I Can't See Any Repo Here

**Comment by ragnarok22** [comment]
This fonts are from 6 years ago. Are they still working?

**Comment by udoyen** [comment]
I would hope so!

**Comment by quangtt-rks** [comment]
> This fonts are from 6 years ago. Are they still working?

This is still working sir, mine is Ubuntu 22.04, WPS 11.1.0.11664
